//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace VirtualClassroom.Services
{
    public partial class Lesson
    {
        public Lesson()
        {
            this.Homeworks = new HashSet<Homework>();
        }
    
        public int Id { get; set; }
        public int SubjectId { get; set; }
        public string Name { get; set; }
        public System.DateTime Date { get; set; }
        public byte[] HomeworkContent { get; set; }
        public byte[] Content { get; set; }
        public string ContentFilename { get; set; }
        public Nullable<System.DateTime> HomeworkDeadline { get; set; }
        public string HomeworkFilename { get; set; }
    
        public virtual ICollection<Homework> Homeworks { get; set; }
    }
    
}
