//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace VirtualClassroom.Services
{
    public partial class Mark
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int HomeworkId { get; set; }
        public string SubjectName { get; set; }
        public string LessonName { get; set; }
        public float Value { get; set; }
    }
    
}
