//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace VirtualClassroom.Services
{
    public partial class VirtualClassroomEntities : DbContext
    {
        public VirtualClassroomEntities()
            : base("name=VirtualClassroomEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //throw new UnintentionalCodeFirstException();
            modelBuilder.Entity<Class>().
                HasMany(c => c.Subjects).
                WithMany(s => s.Classes).
                Map(
                    m =>
                    {
                        m.MapLeftKey("ClassId");
                        m.MapRightKey("SubjectId");
                        m.ToTable("Classes_Subjects");
                    }
                );
        }
    
        public DbSet<Class> Classes { get; set; }
        public DbSet<Homework> Homeworks { get; set; }
        public DbSet<Lesson> Lessons { get; set; }
        public DbSet<Mark> Marks { get; set; }
        public DbSet<Student> Students { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<Teacher> Teachers { get; set; }
    }
}
