//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("swaguche_virtualclassroomModel", "Students_ibfk_1", "Classes", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VirtualClassroom.Services.ClassEntity), "Students", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualClassroom.Services.StudentEntity), true)]
[assembly: EdmRelationshipAttribute("swaguche_virtualclassroomModel", "Homeworks_ibfk_2", "Students", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VirtualClassroom.Services.StudentEntity), "Homeworks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualClassroom.Services.HomeworkEntity), true)]
[assembly: EdmRelationshipAttribute("swaguche_virtualclassroomModel", "Homeworks_ibfk_3", "Lessons", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VirtualClassroom.Services.LessonEntity), "Homeworks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualClassroom.Services.HomeworkEntity), true)]
[assembly: EdmRelationshipAttribute("swaguche_virtualclassroomModel", "Marks_ibfk_1", "Homeworks", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VirtualClassroom.Services.HomeworkEntity), "Marks", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualClassroom.Services.MarkEntity), true)]
[assembly: EdmRelationshipAttribute("swaguche_virtualclassroomModel", "Lessons_ibfk_1", "Subjects", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VirtualClassroom.Services.SubjectEntity), "Lessons", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualClassroom.Services.LessonEntity), true)]
[assembly: EdmRelationshipAttribute("swaguche_virtualclassroomModel", "Subjects_ibfk_1", "Teachers", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(VirtualClassroom.Services.TeacherEntity), "Subjects", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualClassroom.Services.SubjectEntity), true)]
[assembly: EdmRelationshipAttribute("swaguche_virtualclassroomModel", "Classes_Subjects", "Classes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualClassroom.Services.ClassEntity), "Subjects", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(VirtualClassroom.Services.SubjectEntity))]

#endregion

namespace VirtualClassroom.Services
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class VirtualClassroomEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new VirtualClassroomEntities object using the connection string found in the 'VirtualClassroomEntities' section of the application configuration file.
        /// </summary>
        public VirtualClassroomEntities() : base("name=VirtualClassroomEntities", "VirtualClassroomEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VirtualClassroomEntities object.
        /// </summary>
        public VirtualClassroomEntities(string connectionString) : base(connectionString, "VirtualClassroomEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new VirtualClassroomEntities object.
        /// </summary>
        public VirtualClassroomEntities(EntityConnection connection) : base(connection, "VirtualClassroomEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ClassEntity> ClassEntities
        {
            get
            {
                if ((_ClassEntities == null))
                {
                    _ClassEntities = base.CreateObjectSet<ClassEntity>("ClassEntities");
                }
                return _ClassEntities;
            }
        }
        private ObjectSet<ClassEntity> _ClassEntities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<HomeworkEntity> Homeworks
        {
            get
            {
                if ((_Homeworks == null))
                {
                    _Homeworks = base.CreateObjectSet<HomeworkEntity>("Homeworks");
                }
                return _Homeworks;
            }
        }
        private ObjectSet<HomeworkEntity> _Homeworks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<LessonEntity> LessonEntities
        {
            get
            {
                if ((_LessonEntities == null))
                {
                    _LessonEntities = base.CreateObjectSet<LessonEntity>("LessonEntities");
                }
                return _LessonEntities;
            }
        }
        private ObjectSet<LessonEntity> _LessonEntities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<MarkEntity> MarkEntities
        {
            get
            {
                if ((_MarkEntities == null))
                {
                    _MarkEntities = base.CreateObjectSet<MarkEntity>("MarkEntities");
                }
                return _MarkEntities;
            }
        }
        private ObjectSet<MarkEntity> _MarkEntities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StudentEntity> StudentEntities
        {
            get
            {
                if ((_StudentEntities == null))
                {
                    _StudentEntities = base.CreateObjectSet<StudentEntity>("StudentEntities");
                }
                return _StudentEntities;
            }
        }
        private ObjectSet<StudentEntity> _StudentEntities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SubjectEntity> SubjectEntities
        {
            get
            {
                if ((_SubjectEntities == null))
                {
                    _SubjectEntities = base.CreateObjectSet<SubjectEntity>("SubjectEntities");
                }
                return _SubjectEntities;
            }
        }
        private ObjectSet<SubjectEntity> _SubjectEntities;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TeacherEntity> TeacherEntities
        {
            get
            {
                if ((_TeacherEntities == null))
                {
                    _TeacherEntities = base.CreateObjectSet<TeacherEntity>("TeacherEntities");
                }
                return _TeacherEntities;
            }
        }
        private ObjectSet<TeacherEntity> _TeacherEntities;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ClassEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClassEntities(ClassEntity classEntity)
        {
            base.AddObject("ClassEntities", classEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Homeworks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToHomeworks(HomeworkEntity homeworkEntity)
        {
            base.AddObject("Homeworks", homeworkEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the LessonEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLessonEntities(LessonEntity lessonEntity)
        {
            base.AddObject("LessonEntities", lessonEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the MarkEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToMarkEntities(MarkEntity markEntity)
        {
            base.AddObject("MarkEntities", markEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StudentEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudentEntities(StudentEntity studentEntity)
        {
            base.AddObject("StudentEntities", studentEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SubjectEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSubjectEntities(SubjectEntity subjectEntity)
        {
            base.AddObject("SubjectEntities", subjectEntity);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TeacherEntities EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTeacherEntities(TeacherEntity teacherEntity)
        {
            base.AddObject("TeacherEntities", teacherEntity);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="swaguche_virtualclassroomModel", Name="ClassEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ClassEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ClassEntity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="number">Initial value of the Number property.</param>
        /// <param name="letter">Initial value of the Letter property.</param>
        public static ClassEntity CreateClassEntity(global::System.Int32 id, global::System.Int32 number, global::System.String letter)
        {
            ClassEntity classEntity = new ClassEntity();
            classEntity.Id = id;
            classEntity.Number = number;
            classEntity.Letter = letter;
            return classEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Number
        {
            get
            {
                return _Number;
            }
            set
            {
                OnNumberChanging(value);
                ReportPropertyChanging("Number");
                _Number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Number");
                OnNumberChanged();
            }
        }
        private global::System.Int32 _Number;
        partial void OnNumberChanging(global::System.Int32 value);
        partial void OnNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Letter
        {
            get
            {
                return _Letter;
            }
            set
            {
                OnLetterChanging(value);
                ReportPropertyChanging("Letter");
                _Letter = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Letter");
                OnLetterChanged();
            }
        }
        private global::System.String _Letter;
        partial void OnLetterChanging(global::System.String value);
        partial void OnLetterChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("swaguche_virtualclassroomModel", "Students_ibfk_1", "Students")]
        public EntityCollection<StudentEntity> Students
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentEntity>("swaguche_virtualclassroomModel.Students_ibfk_1", "Students");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentEntity>("swaguche_virtualclassroomModel.Students_ibfk_1", "Students", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("swaguche_virtualclassroomModel", "Classes_Subjects", "Subjects")]
        public EntityCollection<SubjectEntity> Subjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SubjectEntity>("swaguche_virtualclassroomModel.Classes_Subjects", "Subjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SubjectEntity>("swaguche_virtualclassroomModel.Classes_Subjects", "Subjects", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="swaguche_virtualclassroomModel", Name="HomeworkEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class HomeworkEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new HomeworkEntity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="studentId">Initial value of the StudentId property.</param>
        /// <param name="lessonId">Initial value of the LessonId property.</param>
        /// <param name="content">Initial value of the Content property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static HomeworkEntity CreateHomeworkEntity(global::System.Int32 id, global::System.Int32 studentId, global::System.Int32 lessonId, global::System.Byte[] content, global::System.DateTime date)
        {
            HomeworkEntity homeworkEntity = new HomeworkEntity();
            homeworkEntity.Id = id;
            homeworkEntity.StudentId = studentId;
            homeworkEntity.LessonId = lessonId;
            homeworkEntity.Content = content;
            homeworkEntity.Date = date;
            return homeworkEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentId
        {
            get
            {
                return _StudentId;
            }
            set
            {
                OnStudentIdChanging(value);
                ReportPropertyChanging("StudentId");
                _StudentId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentId");
                OnStudentIdChanged();
            }
        }
        private global::System.Int32 _StudentId;
        partial void OnStudentIdChanging(global::System.Int32 value);
        partial void OnStudentIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LessonId
        {
            get
            {
                return _LessonId;
            }
            set
            {
                OnLessonIdChanging(value);
                ReportPropertyChanging("LessonId");
                _LessonId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LessonId");
                OnLessonIdChanged();
            }
        }
        private global::System.Int32 _LessonId;
        partial void OnLessonIdChanging(global::System.Int32 value);
        partial void OnLessonIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Byte[] Content
        {
            get
            {
                return StructuralObject.GetValidValue(_Content);
            }
            set
            {
                OnContentChanging(value);
                ReportPropertyChanging("Content");
                _Content = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Content");
                OnContentChanged();
            }
        }
        private global::System.Byte[] _Content;
        partial void OnContentChanging(global::System.Byte[] value);
        partial void OnContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("swaguche_virtualclassroomModel", "Homeworks_ibfk_2", "Students")]
        public StudentEntity Student
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentEntity>("swaguche_virtualclassroomModel.Homeworks_ibfk_2", "Students").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentEntity>("swaguche_virtualclassroomModel.Homeworks_ibfk_2", "Students").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<StudentEntity> StudentReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentEntity>("swaguche_virtualclassroomModel.Homeworks_ibfk_2", "Students");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<StudentEntity>("swaguche_virtualclassroomModel.Homeworks_ibfk_2", "Students", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("swaguche_virtualclassroomModel", "Homeworks_ibfk_3", "Lessons")]
        public LessonEntity Lesson
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LessonEntity>("swaguche_virtualclassroomModel.Homeworks_ibfk_3", "Lessons").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LessonEntity>("swaguche_virtualclassroomModel.Homeworks_ibfk_3", "Lessons").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<LessonEntity> LessonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<LessonEntity>("swaguche_virtualclassroomModel.Homeworks_ibfk_3", "Lessons");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<LessonEntity>("swaguche_virtualclassroomModel.Homeworks_ibfk_3", "Lessons", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("swaguche_virtualclassroomModel", "Marks_ibfk_1", "Marks")]
        public EntityCollection<MarkEntity> Marks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<MarkEntity>("swaguche_virtualclassroomModel.Marks_ibfk_1", "Marks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<MarkEntity>("swaguche_virtualclassroomModel.Marks_ibfk_1", "Marks", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="swaguche_virtualclassroomModel", Name="LessonEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class LessonEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new LessonEntity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="subjectId">Initial value of the SubjectId property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="date">Initial value of the Date property.</param>
        public static LessonEntity CreateLessonEntity(global::System.Int32 id, global::System.Int32 subjectId, global::System.String name, global::System.DateTime date)
        {
            LessonEntity lessonEntity = new LessonEntity();
            lessonEntity.Id = id;
            lessonEntity.SubjectId = subjectId;
            lessonEntity.Name = name;
            lessonEntity.Date = date;
            return lessonEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SubjectId
        {
            get
            {
                return _SubjectId;
            }
            set
            {
                OnSubjectIdChanging(value);
                ReportPropertyChanging("SubjectId");
                _SubjectId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SubjectId");
                OnSubjectIdChanged();
            }
        }
        private global::System.Int32 _SubjectId;
        partial void OnSubjectIdChanging(global::System.Int32 value);
        partial void OnSubjectIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private global::System.DateTime _Date;
        partial void OnDateChanging(global::System.DateTime value);
        partial void OnDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> HomeworkDueDate
        {
            get
            {
                return _HomeworkDueDate;
            }
            set
            {
                OnHomeworkDueDateChanging(value);
                ReportPropertyChanging("HomeworkDueDate");
                _HomeworkDueDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HomeworkDueDate");
                OnHomeworkDueDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _HomeworkDueDate;
        partial void OnHomeworkDueDateChanging(Nullable<global::System.DateTime> value);
        partial void OnHomeworkDueDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] HomeworkContent
        {
            get
            {
                return StructuralObject.GetValidValue(_HomeworkContent);
            }
            set
            {
                OnHomeworkContentChanging(value);
                ReportPropertyChanging("HomeworkContent");
                _HomeworkContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomeworkContent");
                OnHomeworkContentChanged();
            }
        }
        private global::System.Byte[] _HomeworkContent;
        partial void OnHomeworkContentChanging(global::System.Byte[] value);
        partial void OnHomeworkContentChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("swaguche_virtualclassroomModel", "Homeworks_ibfk_3", "Homeworks")]
        public EntityCollection<HomeworkEntity> Homeworks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HomeworkEntity>("swaguche_virtualclassroomModel.Homeworks_ibfk_3", "Homeworks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HomeworkEntity>("swaguche_virtualclassroomModel.Homeworks_ibfk_3", "Homeworks", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("swaguche_virtualclassroomModel", "Lessons_ibfk_1", "Subjects")]
        public SubjectEntity Subject
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SubjectEntity>("swaguche_virtualclassroomModel.Lessons_ibfk_1", "Subjects").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SubjectEntity>("swaguche_virtualclassroomModel.Lessons_ibfk_1", "Subjects").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<SubjectEntity> SubjectReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<SubjectEntity>("swaguche_virtualclassroomModel.Lessons_ibfk_1", "Subjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<SubjectEntity>("swaguche_virtualclassroomModel.Lessons_ibfk_1", "Subjects", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="swaguche_virtualclassroomModel", Name="MarkEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class MarkEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new MarkEntity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        /// <param name="homeworkId">Initial value of the HomeworkId property.</param>
        public static MarkEntity CreateMarkEntity(global::System.Int32 id, global::System.Int32 value, global::System.Int32 homeworkId)
        {
            MarkEntity markEntity = new MarkEntity();
            markEntity.Id = id;
            markEntity.Value = value;
            markEntity.HomeworkId = homeworkId;
            return markEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Int32 _Value;
        partial void OnValueChanging(global::System.Int32 value);
        partial void OnValueChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 HomeworkId
        {
            get
            {
                return _HomeworkId;
            }
            set
            {
                OnHomeworkIdChanging(value);
                ReportPropertyChanging("HomeworkId");
                _HomeworkId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HomeworkId");
                OnHomeworkIdChanged();
            }
        }
        private global::System.Int32 _HomeworkId;
        partial void OnHomeworkIdChanging(global::System.Int32 value);
        partial void OnHomeworkIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("swaguche_virtualclassroomModel", "Marks_ibfk_1", "Homeworks")]
        public HomeworkEntity Homework
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HomeworkEntity>("swaguche_virtualclassroomModel.Marks_ibfk_1", "Homeworks").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HomeworkEntity>("swaguche_virtualclassroomModel.Marks_ibfk_1", "Homeworks").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<HomeworkEntity> HomeworkReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<HomeworkEntity>("swaguche_virtualclassroomModel.Marks_ibfk_1", "Homeworks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<HomeworkEntity>("swaguche_virtualclassroomModel.Marks_ibfk_1", "Homeworks", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="swaguche_virtualclassroomModel", Name="StudentEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StudentEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StudentEntity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="middleName">Initial value of the MiddleName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="eGN">Initial value of the EGN property.</param>
        /// <param name="passwordHash">Initial value of the PasswordHash property.</param>
        /// <param name="classId">Initial value of the ClassId property.</param>
        public static StudentEntity CreateStudentEntity(global::System.Int32 id, global::System.String username, global::System.String firstName, global::System.String middleName, global::System.String lastName, global::System.String eGN, global::System.String passwordHash, global::System.Int32 classId)
        {
            StudentEntity studentEntity = new StudentEntity();
            studentEntity.Id = id;
            studentEntity.Username = username;
            studentEntity.FirstName = firstName;
            studentEntity.MiddleName = middleName;
            studentEntity.LastName = lastName;
            studentEntity.EGN = eGN;
            studentEntity.PasswordHash = passwordHash;
            studentEntity.ClassId = classId;
            return studentEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EGN
        {
            get
            {
                return _EGN;
            }
            set
            {
                OnEGNChanging(value);
                ReportPropertyChanging("EGN");
                _EGN = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EGN");
                OnEGNChanged();
            }
        }
        private global::System.String _EGN;
        partial void OnEGNChanging(global::System.String value);
        partial void OnEGNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PasswordHash
        {
            get
            {
                return _PasswordHash;
            }
            set
            {
                OnPasswordHashChanging(value);
                ReportPropertyChanging("PasswordHash");
                _PasswordHash = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PasswordHash");
                OnPasswordHashChanged();
            }
        }
        private global::System.String _PasswordHash;
        partial void OnPasswordHashChanging(global::System.String value);
        partial void OnPasswordHashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClassId
        {
            get
            {
                return _ClassId;
            }
            set
            {
                OnClassIdChanging(value);
                ReportPropertyChanging("ClassId");
                _ClassId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ClassId");
                OnClassIdChanged();
            }
        }
        private global::System.Int32 _ClassId;
        partial void OnClassIdChanging(global::System.Int32 value);
        partial void OnClassIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("swaguche_virtualclassroomModel", "Students_ibfk_1", "Classes")]
        public ClassEntity Class
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClassEntity>("swaguche_virtualclassroomModel.Students_ibfk_1", "Classes").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClassEntity>("swaguche_virtualclassroomModel.Students_ibfk_1", "Classes").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ClassEntity> ClassReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ClassEntity>("swaguche_virtualclassroomModel.Students_ibfk_1", "Classes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ClassEntity>("swaguche_virtualclassroomModel.Students_ibfk_1", "Classes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("swaguche_virtualclassroomModel", "Homeworks_ibfk_2", "Homeworks")]
        public EntityCollection<HomeworkEntity> Homeworks
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<HomeworkEntity>("swaguche_virtualclassroomModel.Homeworks_ibfk_2", "Homeworks");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<HomeworkEntity>("swaguche_virtualclassroomModel.Homeworks_ibfk_2", "Homeworks", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="swaguche_virtualclassroomModel", Name="SubjectEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SubjectEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SubjectEntity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="name">Initial value of the Name property.</param>
        /// <param name="teacherId">Initial value of the TeacherId property.</param>
        public static SubjectEntity CreateSubjectEntity(global::System.Int32 id, global::System.String name, global::System.Int32 teacherId)
        {
            SubjectEntity subjectEntity = new SubjectEntity();
            subjectEntity.Id = id;
            subjectEntity.Name = name;
            subjectEntity.TeacherId = teacherId;
            return subjectEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeacherId
        {
            get
            {
                return _TeacherId;
            }
            set
            {
                OnTeacherIdChanging(value);
                ReportPropertyChanging("TeacherId");
                _TeacherId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TeacherId");
                OnTeacherIdChanged();
            }
        }
        private global::System.Int32 _TeacherId;
        partial void OnTeacherIdChanging(global::System.Int32 value);
        partial void OnTeacherIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("swaguche_virtualclassroomModel", "Lessons_ibfk_1", "Lessons")]
        public EntityCollection<LessonEntity> Lessons
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<LessonEntity>("swaguche_virtualclassroomModel.Lessons_ibfk_1", "Lessons");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<LessonEntity>("swaguche_virtualclassroomModel.Lessons_ibfk_1", "Lessons", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("swaguche_virtualclassroomModel", "Subjects_ibfk_1", "Teachers")]
        public TeacherEntity Teacher
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TeacherEntity>("swaguche_virtualclassroomModel.Subjects_ibfk_1", "Teachers").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TeacherEntity>("swaguche_virtualclassroomModel.Subjects_ibfk_1", "Teachers").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TeacherEntity> TeacherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TeacherEntity>("swaguche_virtualclassroomModel.Subjects_ibfk_1", "Teachers");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TeacherEntity>("swaguche_virtualclassroomModel.Subjects_ibfk_1", "Teachers", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("swaguche_virtualclassroomModel", "Classes_Subjects", "Classes")]
        public EntityCollection<ClassEntity> Classes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ClassEntity>("swaguche_virtualclassroomModel.Classes_Subjects", "Classes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ClassEntity>("swaguche_virtualclassroomModel.Classes_Subjects", "Classes", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="swaguche_virtualclassroomModel", Name="TeacherEntity")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TeacherEntity : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TeacherEntity object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="username">Initial value of the Username property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="middleName">Initial value of the MiddleName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="passwordHash">Initial value of the PasswordHash property.</param>
        public static TeacherEntity CreateTeacherEntity(global::System.Int32 id, global::System.String username, global::System.String firstName, global::System.String middleName, global::System.String lastName, global::System.String passwordHash)
        {
            TeacherEntity teacherEntity = new TeacherEntity();
            teacherEntity.Id = id;
            teacherEntity.Username = username;
            teacherEntity.FirstName = firstName;
            teacherEntity.MiddleName = middleName;
            teacherEntity.LastName = lastName;
            teacherEntity.PasswordHash = passwordHash;
            return teacherEntity;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Username
        {
            get
            {
                return _Username;
            }
            set
            {
                OnUsernameChanging(value);
                ReportPropertyChanging("Username");
                _Username = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Username");
                OnUsernameChanged();
            }
        }
        private global::System.String _Username;
        partial void OnUsernameChanging(global::System.String value);
        partial void OnUsernameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PasswordHash
        {
            get
            {
                return _PasswordHash;
            }
            set
            {
                OnPasswordHashChanging(value);
                ReportPropertyChanging("PasswordHash");
                _PasswordHash = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("PasswordHash");
                OnPasswordHashChanged();
            }
        }
        private global::System.String _PasswordHash;
        partial void OnPasswordHashChanging(global::System.String value);
        partial void OnPasswordHashChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("swaguche_virtualclassroomModel", "Subjects_ibfk_1", "Subjects")]
        public EntityCollection<SubjectEntity> Subjects
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SubjectEntity>("swaguche_virtualclassroomModel.Subjects_ibfk_1", "Subjects");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SubjectEntity>("swaguche_virtualclassroomModel.Subjects_ibfk_1", "Subjects", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
