//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace VirtualClassroom.Services
{
    public partial class Student
    {
        public Student()
        {
            this.Homeworks = new HashSet<Homework>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string EGN { get; set; }
        public string PasswordHash { get; set; }
        public int ClassId { get; set; }
    
        public virtual Class Class { get; set; }
        public virtual ICollection<Homework> Homeworks { get; set; }
    }
    
}
